/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BettingMarket } from "./BettingMarket";
export * as factories from "./factories";
export { BettingMarket__factory } from "./factories/BettingMarket__factory";
